### ISSUE TITLE
make `navbarLoggedIn` component central to the whole application.

### ISSUE THREAD

**Issue by vantage-ola** [vantage-ola/tracknow#98]
instead of repeating the component a lot of times. you should ideally only render it once and make it central across the app.

in `Home.tsx` 
`<NavbarLoggedIn name={username} pp={profilePic} onOpen={onOpen} />`

same in `UserProfile.tsx` and multiple others
`<NavbarLoggedIn name={username} pp={profilePic} onOpen={onOpen} />`

Ideally, you should be  place it in one component and not in multiple components. i think it slows the app down,

**Comment by Sultan-Ubiquitous** [comment]
Hey there, I am working on this issue.
I have a question regarding the backend, when creating .env file what exactly is API_KEY referring to?
Thank you :smile:

**Comment by vantage-ola** [comment]
> Hey there, I am working on this issue. I have a question regarding the backend, when creating .env file what exactly is API_KEY referring to? Thank you 😄

sorry for responding late. @Sultan-Ubiquitous 
the api key is the key you include in the headers when making a request to the backend. so you can generate something secret to use.
for example, 

```
    const response = await fetch(endpoints.GET_USERS, {
        method: 'GET',
        headers: {
            'Content-Type': 'application/json',
            'x-api-key': API_KEY
        }
    });
```

**Comment by vantage-ola** [comment]
#120 first two commits squash this issue.
